const additionalData = [
  {
    name: "James Smith",
    fname: "James",
    lname: "Smith",
    age: 32,
    role: "Manager",
    zipCode: "12345",
    activeStatus: "Active",
    deleted: "true",
    gender: "male",
  },
  {
    name: "Emily Johnson",
    fname: "Emily",
    lname: "Johnson",
    age: 28,
    role: "Developer",
    zipCode: "67890",
    activeStatus: "Inactive",
    deleted: "false",
    gender: "female",
  },
  {
    name: "Michael Williams",
    fname: "Michael",
    lname: "Williams",
    age: 35,
    role: "Designer",
    zipCode: "54321",
    activeStatus: "Active",
    deleted: "false",
    gender: "male",
  },
  // END: abpxx6d04wxr
  // BEGIN: be15d9bcejpp
  {
    name: "Wendy Williams",
    fname: "Samuel",
    lname: "Williams",
    age: 35,
    role: "Manager",
    zipCode: "54321",
    activeStatus: "Inactive",
    deleted: "false",
    gender: "female",
  },
  {
    name: "Emma Brown",
    fname: "Emma",
    lname: "Brown",
    age: 27,
    role: "Manager",
    zipCode: "09876",
    activeStatus: "Inactive",
    deleted: "true",
    gender: "female",
  },
  {
    name: "Daniel Jones",
    fname: "Daniel",
    lname: "Jones",
    age: 31,
    role: "Developer",
    zipCode: "13579",
    activeStatus: "Active",
    deleted: "false",
    gender: "male",
  },
  {
    name: "Olivia Davis",
    fname: "Olivia",
    lname: "Davis",
    age: 29,
    role: "Designer",
    zipCode: "24680",
    activeStatus: "Inactive",
    deleted: "true",
    gender: "female",
  },
  {
    name: "Matthew Miller",
    fname: "Matthew",
    lname: "Miller",
    age: 33,
    role: "Manager",
    zipCode: "97531",
    activeStatus: "Active",
    deleted: "false",
    gender: "male",
  },
  {
    name: "Ava Wilson",
    fname: "Ava",
    lname: "Wilson",
    age: 26,
    role: "Developer",
    zipCode: "86420",
    activeStatus: "Inactive",
    deleted: "false",
    gender: "female",
  },
  {
    name: "Sophia Anderson",
    fname: "Sophia",
    lname: "Anderson",
    age: 30,
    role: "Developer",
    zipCode: "86420",
    activeStatus: "Inactive",
    deleted: "false",
    gender: "female",
  },
  // END: be15d9bcejpp
];

export const data = [
  {
    name: "John Doe",
    fname: "John",
    lname: "Doe",
    age: 30,
    role: "Developer",
    zipCode: "32145",
    activeStatus: "Active",
    deleted: "false",
    gender: "male",
  },
  {
    name: "Jane Doe",
    fname: "Jane",
    lname: "Doe",
    age: 25,
    role: "Designer",
    zipCode: "48451",
    activeStatus: "Inactive",
    deleted: "true",
    gender: "other",
  },
  ...additionalData,
];

export const columns = [
  { title: "Name", dataIndex: "name" },
  { title: "First Name", dataIndex: "fname" },
  { title: "Last Name", dataIndex: "lname" },
  { title: "Gender", dataIndex: "gender" },
  { title: "Age", dataIndex: "age" },
  { title: "Zip Code", dataIndex: "zipCode" },
  { title: "Role", dataIndex: "role" },
];
